#! /bin/sh
#
# The idea to this kind of setup info script was stolen from numerous
# other packages, such as neon, libxml and gnome.
#
# $Id: curl-config.in,v 1.15 2002/09/02 22:45:46 bagder Exp $
#
prefix=/usr
exec_prefix=${prefix}
includedir=${prefix}/include

usage()
{
    cat <<EOF
Usage: curl-config [OPTION]

Available values for OPTION include:

  --ca        ca bundle install path
  --cc        compiler
  --cflags    pre-processor and compiler flags
  --feature   newline separated list of enabled features
  --help      display this help and exit
  --libs      library linking information
  --prefix    curl install prefix
  --version   output version information
  --vernum    output the version information as a number (hexadecimal)
EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

while test $# -gt 0; do
    case "$1" in
    # this deals with options in the style
    # --option=value and extracts the value part
    # [not currently used]
    -*=*) value=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) value= ;;
    esac

    case "$1" in
    --ca)
	echo /usr/share/curl/curl-ca-bundle.crt
	;;

    --cc)
	echo gcc
	;;

    --prefix)
	echo $prefix
	;;

    --feature)
	if test "1" = "1"; then
          echo "SSL"
        fi
	if test "" = "1"; then
          echo "KRB4"
        fi
	if test "" = "1"; then
          echo "IPv6"
        fi
	if test "1" = "1"; then
          echo "libz"
        fi
	if test "" = "1"; then
          echo "HTTP-disabled"
        fi
	if test "" = "1"; then
          echo "FTP-disabled"
        fi
	if test "" = "1"; then
          echo "GOPHER-disabled"
        fi
	if test "" = "1"; then
          echo "FILE-disabled"
        fi
	if test "" = "1"; then
          echo "TELNET-disabled"
        fi
	if test "" = "1"; then
          echo "LDAP-disabled"
        fi
	if test "" = "1"; then
          echo "DICT-disabled"
        fi
	;;

    --version)
	echo libcurl 7.10.2
	exit 0
	;;

    --vernum)
	echo 070a02
	exit 0
	;;

    --help)
	usage 0
	;;

    --cflags)
       	echo -I${prefix}/include
       	;;

    --libs)
       	echo -L${exec_prefix}/lib -lcurl  -lz -lssl -lcrypto  -lz
       	;;

    *)
        echo "unknown option: $1"
	usage
	exit 1
	;;
    esac
    shift
done

exit 0
